### ISSUE TITLE
Nuget packages incompatibility

### ISSUE THREAD

**Issue by oikos99** [WebineersCPP/ClassTrack#10]
Trying to get some nice PDF plugins but receiving this error:

One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Please look into it at your leisure as this is not our top priority as of now....

**Comment by oikos99** [comment]
Found this similar issue:

https://github.com/dotnet/cli/issues/3703

**Comment by nliupeng** [comment]
HtmlUtilityPack succesfully imported :)
