### ISSUE TITLE
Hard code list of Majors and their Subplans

### ISSUE THREAD

**Issue by nliupeng** [WebineersCPP/ClassTrack#15]
This list is going to be used to be displayed in App/Home#/add
The picture belows retrieves data from DB.

Check Models/ClassTrackContextSeedData.cs
Check Models/CPPMajor.cs
Check Models/CPPSubplan.cs

The below code creates a CPPMajor object, which contains a list of CPPSubplan objects.
_context is used to connect to database.
Our task: to create all CPPMajors, and for those majors who have subplans, fill their List<CPPSubplan>

CPPMajor major = new CPPMajor()
                {
                    Title = "Computer Science"
                };
                _context.CPPMajors.Add(major);
                major = new CPPMajor()
                {
                    Title = "Business Administration",
                    Subplans = new List<CPPSubplan>()
                    {
                        new CPPSubplan() { Title = "Accounting" },
                        new CPPSubplan() { Title = "Computer Information Systems" },
                        new CPPSubplan() { Title = "E-Business" },
                        new CPPSubplan() { Title = "Finance, Real Estate, and Law" },
                        new CPPSubplan() { Title = "International Business" },
                        new CPPSubplan() { Title = "Management and Human Resources" },
                        new CPPSubplan() { Title = "Marketing Management" },
                        new CPPSubplan() { Title = "Technology and Operations Management" },
                    } 
                };
                _context.CPPMajors.Add(major);
                major = new CPPMajor()
                {
                    Title = "Communication"
                };
                _context.CPPMajors.Add(major);
                major = new CPPMajor()
                {
                    Title = "History"
                };
                _context.CPPMajors.Add(major);

![add](https://cloud.githubusercontent.com/assets/14900902/20654202/d96fb264-b4cb-11e6-8b74-4e1fc1894396.png)

**Comment by IanStodart** [comment]
Done 
[Majors and Subplans.txt](https://github.com/WebineersCPP/ClassTrack/files/615929/Majors.and.Subplans.txt)
