### ISSUE TITLE
VB database error

### ISSUE THREAD

**Issue by oikos99** [WebineersCPP/ClassTrack#2]
Did everyone get this issue resolved??  Visual Studio was not compiling correctly as Ian suggested

**Comment by andreaschmidt95** [comment]
It compiles for me, but there's an error when the code is run. But I mean, it's not exactly finished/whole yet, sooo

**Comment by nliupeng** [comment]
@oikos99 did you get the issue resolved? 
@andreaschmidt95 what kind of error are you receiving?

Everyone should have already a local database set up in the project. I'll explain further about how to deal with migrations and update your database from the remote repo when the time comes, but as of now please do let me know if there are any issues with the initial database.

**Comment by oikos99** [comment]
@nliupeng yes! works now.... thanks Nelly~ :)
