### ISSUE TITLE
Convert html to .json

### ISSUE THREAD

**Issue by andreaschmidt95** [WebineersCPP/ClassTrack#4]
1) research a potential library for html parsing 2) create a json file from the info in the university catalog from each major (first for just cs majors, then figure out how to apply it to other majors)

**Comment by oikos99** [comment]
is this what you'll be doing Andrea?  we have yet to decide the main functionalities of our project!?

**Comment by oikos99** [comment]
I have added a Visual Studio Nuget (library) that is equivalent to JSoup called Html Agility Pack

Look into it

http://stackoverflow.com/questions/846994/how-to-use-html-agility-pack

**Comment by oikos99** [comment]
Just done the first part of retrieving information from a HTML catalog link and convert useful data into a CurriculumSheet object.
